[project]
name = "SMESH"
version = "0.1.0"
description = "Add a short description here"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64", "linux-aarch64"]

[environments]
prepare = ["prepare"]
createsource = ["createsource"]
build = ["build"]

# prepare sources (copy and patch)
[feature.prepare.dependencies]
git = "*"
python-patch = "*"
python = "*"

[feature.prepare.tasks]
initialize = "git submodule update --init"
prepare = { cmd = "python prepare.py", depends-on = ["initialize"]}


# create release source
[feature.createsource]
platforms = ["linux-64", "osx-64", "osx-arm64", "linux-aarch64"]

[feature.createsource.dependencies]
tar = "*"

[feature.createsource.tasks]
create_source = { cmd = ["tar", "czvf", "SMESH_$(git branch --show-current).tar.gz",
                         "src", "test", "CMakeLists.txt", "cmake/SMESHConfig.cmake.in", 
                         "LICENSE.txt", "README.md"], depends-on = [ "prepare" ]}

[feature.build.dependencies]
vtk = ">=9.3.1,<9.4"
occt = ">=7.8.1,<7.9"
libzlib = ">=1.3.1,<1.4"
libboost-devel = ">=1.85.0,<1.86"
cmake = ">=3.30.0,<3.31"
zlib = ">=1.3.1,<1.4"
catch2 = "<3.0"


# build and test
[feature.build.tasks]
configure = { cmd = ["cmake", 
                     "-S", ".",
                     "-D", "CMAKE_BUILD_TYPE='Debug'",
                     "-D", "CMAKE_INSTALL_PREFIX:FILEPATH=$CONDA_PREFIX",
                     "-D", "CMAKE_INSTALL_RPATH=$CONDA_PREFIX/lib",
                     "-D", "ENABLE_NETGEN=ON",
                     "-B", "build"], depends-on = ["prepare"]}
build = { cmd = ["make", "-C", "build", "install"], depends-on = ["configure"] }
build_only = { cmd = ["make", "-C", "build", "install"] }
configure_tests = { cmd = ["cmake", 
                           "-S", "test/.",
                           "-D", "CMAKE_BUILD_TYPE='Debug'",
                           "-D", "CMAKE_PREFIX_PATH=$CONDA_PREFIX",
                           "-D", "CMAKE_INSTALL_RPATH=$CONDA_PREFIX/lib",
                           "-B", "test/build"]}
build_tests = { cmd = ["make", "-C", "test/build", "-j4", 
                         "install"], depends-on = ["configure_tests"]}
test = { cmd = ["./test/tests/test_Catch", "&&",
                     "./test/tests/test_MEFISTO2", "&&", 
                     "./test/tests/test_StdMeshers", "&&",
                     "./test/tests/test_NETGENPlugin"], depends-on = ["build_tests"] }
clean = { cmd = ["rm", "-r", "build", "test/build", "test/tests"] }
gdb_mefisto = { cmd = ["gdb", "./test/tests/test_MEFISTO2"]} # linux
gdb_std = { cmd = ["gdb", "./test/tests/test_StdMesher"]} # linux
gdb_netgen = { cmd = ["gdb", "./test/tests/test_NETGENPlugin"]} # linux
lldb_mefisto = { cmd = ["lldb", "./test/tests/test_MEFISTO2"]} # osx
