[project]
name = "SMESH"
version = "0.1.0"
description = "Add a short description here"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64", "linux-aarch64"]

[environments]
prepare = ["prepare"]
create_source = ["create_source"]

# prepare sources (copy and patch)
[feature.prepare.dependencies]
git = "*"
python-patch = "*"
python = "*"

[feature.prepare.tasks]
initialize = "git submodule update --init"
prepare = { cmd = "python prepare.py", depends-on = ["initialize"]}


# create release source
[feature.create_source]
platforms = ["linux-64", "osx-64", "osx-arm64", "linux-aarch64"]

[feature.create_source.dependencies]
tar = "*"

[feature.create_source.tasks]
create_source = { cmd = ["tar", "czvf", "SMESH_$(git branch --show-current).tar.gz",
                         "src", "test", "CMakeLists.txt", "cmake/SMESHConfig.cmake.in", 
                         "LICENSE.txt", "README.md"], depends-on = [ "prepare" ]}

[dependencies]
ninja = "*"
vtk = ">=9.4.0,<9.5"
occt = ">=7.9.0,<7.10"
libzlib = "*"
libboost-devel = "*"
cmake = "*"
zlib = "*"
catch2 = "<3.0"

[target.win-64.dependencies]
pthreads-win32 = "*"

# build and test
[tasks]
configure = { cmd = ["cmake", "-G", "Ninja", "-B", "build", "-S", ".",
                     "-D", "CMAKE_BUILD_TYPE='Debug'",
                     "-D", "CMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
                     "-D", "CMAKE_INSTALL_RPATH=$CONDA_PREFIX/lib",
                     "-D", "ENABLE_NETGEN=ON",
                     "-D", "PTHREAD_INCLUDE_DIRS=$CONDA_PREFIX/include",
                     "-D", "PTHREAD_LIB_DIRS=$CONDA_PREFIX/lib",
                     ], depends-on = ["prepare"]}
build = { cmd = ["ninja", "-C", "build", "install"], depends-on = ["configure"] }
build_only = { cmd = ["ninja", "-C", "build", "install"] }
configure_tests = { cmd = ["cmake", "-G", "Ninja", "-B", "test/build", "-S", "test/.",
                           "-D", "CMAKE_BUILD_TYPE='Debug'",
                           "-D", "CMAKE_PREFIX_PATH=$CONDA_PREFIX",
                           "-D", "CMAKE_INSTALL_RPATH=$CONDA_PREFIX/lib",
                           "-D", "PTHREAD_INCLUDE_DIRS=$CONDA_PREFIX/include",
                           "-D", "PTHREAD_LIB_DIRS=$CONDA_PREFIX/lib",
                           ]}
build_tests = { cmd = ["ninja", "-C", "test/build", "-j4", 
                       "install"], depends-on = ["configure_tests"]}
test = { cmd = ["./test/tests/test_Catch", "&&",
                     "./test/tests/test_MEFISTO2", "&&", 
                     "./test/tests/test_StdMeshers", "&&",
                     "./test/tests/test_NETGENPlugin"], depends-on = ["build_tests"] }
clean = { cmd = ["rm", "-r", "build", "test/build", "test/tests"] }
gdb_mefisto = { cmd = ["gdb", "./test/tests/test_MEFISTO2"]} # linux
gdb_std = { cmd = ["gdb", "./test/tests/test_StdMesher"]} # linux
gdb_netgen = { cmd = ["gdb", "./test/tests/test_NETGENPlugin"]} # linux
lldb_mefisto = { cmd = ["lldb", "./test/tests/test_MEFISTO2"]} # osx
