[project]
name = "SMESH"
version = "0.1.0"
description = "Add a short description here"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64", "linux-aarch64"]


## TODO: find a better solution to add the tar dependency. tar is not available on windows
[target.osx-arm64.dependencies]
tar = "*"

[target.linux-64.dependencies]
tar = "*"

[target.linux-aarch64.dependencies]
tar = "*"

[target.osx-64.dependencies]
tar = "*"


[tasks]
## build tasks
initialize = "git submodule update --init"
prepare = { cmd = "python prepare.py", depends-on = ["initialize"]}
configure = { cmd = ["cmake", 
                     "-S", ".",
                     "-D", "CMAKE_BUILD_TYPE='Debug'",
                     "-D", "CMAKE_INSTALL_PREFIX:FILEPATH=$CONDA_PREFIX",
                     "-D", "CMAKE_INSTALL_RPATH=$CONDA_PREFIX/lib",
                     "-D", "ENABLE_NETGEN=ON",
                     "-B", "build"], depends-on = ["prepare"]}
build = { cmd = ["make", "-C", "build", "install"], depends-on = ["configure"] }

## test tasks
configure_tests = { cmd = ["cmake", 
                           "-S", "test/.",
                           "-D", "CMAKE_BUILD_TYPE='Debug'",
                           "-D", "CMAKE_PREFIX_PATH=$CONDA_PREFIX",
                           "-D", "CMAKE_INSTALL_RPATH=$CONDA_PREFIX/lib",
                           "-B", "test/build"]}
build_tests = { cmd = ["make", "-C", "test/build", "-j4", 
                         "install"], depends-on = ["configure_tests"]}
test = { cmd = ["./test/tests/test_Catch", "&&",
                     "./test/tests/test_MEFISTO2", "&&", 
                     "./test/tests/test_StdMeshers", "&&",
                     "./test/tests/test_NETGENPlugin"], depends-on = ["build_tests"] }

## clean tasks
clean = { cmd = ["rm", "-r", "build", "test/build", "test/tests"] }

## create source
create_source = { cmd = ["tar", "czvf", "SMESH_$(git rev-parse --abbrev-ref HEAD).tar.gz",
                         "src", "test", "CMakeLists.txt"], depends-on = [ "prepare" ]}

[dependencies]
vtk = ">=9.3.1,<9.4"
occt = ">=7.8.1,<7.9"
libzlib = ">=1.3.1,<1.4"
libboost-devel = ">=1.85.0,<1.86"
cmake = ">=3.30.0,<3.31"
git = ">=2.45.2,<2.46"
python-patch = ">=1.16,<2"
python = "3.12.*"
zlib = ">=1.3.1,<1.4"
catch2 = "<3.0"


