name: Build Project

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        
    steps:
      - name: "Clone SMESH"
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: "Configure conda"
        uses: conda-incubator/setup-miniconda@v2
        with:        
          auto-activate-base: true
          activate-environment: "base"

      - name: "Install conda build"
        run: conda install -c conda-forge conda-build python-patch

      - name: "Check conda"
        run: |
          conda info -a
          conda list

      - name: "Install Linux Dependencies"
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libxext-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/ /usr/lib64

      - name: "Prepare sources"
        run: |
          python prepare.py

      - name: "Run conda build"
        run: |
          mkdir conda
          conda build ci/conda -c conda-forge --output-folder conda

      - name: "Upload conda package"
        uses: actions/upload-artifact@v2
        with:
          name: smesh-${{ matrix.os }}
          path: conda
