name: create release

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]


jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true

    - name: Set output
      id: set_tag
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.25.0

    - run: pixi run create_source

    - uses: svenstaro/upload-release-action@v2
      name: Upload binaries to release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: SMESH_*.tar.gz
        tag: ${{ steps.set_tag.outputs.tag }}
        overwrite: true
        file_glob: true