name: create release

on:
  create:
    tags:
      - v*

  workflow_dispatch:
      
jobs:
  create-release:
    runs-on: ubuntu-latest
 
  steps:

  - uses: actions/checkout@v2
    name: Checkout
    submodules: true
    
  - name: Set output
    id: vars
    run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
 
  - name: prepare
    run: |
      wget https://raw.githubusercontent.com/fabacab/git-archive-all.sh/master/git-archive-all.sh
      ./git-archive-all
      mv SMESH.tar.gz SMESH_${{ steps.vars.outputs.tag }}.tar.gz

  - uses: svenstaro/upload-release-action@v2
    name: Upload binaries to release
    with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      file: SMESH_${{ steps.vars.outputs.tag }}.tar.gz
      tag: ${{ steps.vars.outputs.tag }}
      overwrite: true
      file_glob: true
