name: create release

on:
  push:
    branches:    
      - '*' 
  schedule:
   - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.25.0

    - run: pixi run create_source

    - uses: svenstaro/upload-release-action@v2
      name: Upload binaries to release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: SMESH_*.tar.gz
        tag: ${{ steps.vars.outputs.tag }}
        overwrite: true
        file_glob: true