on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - if: matrix.os == 'ubuntu-latest'
      name: "Fix dependencies"
      run: |
          sudo apt-get install mesa-common-dev

    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true

    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.25.0
        cache: true

    - run: pixi run build
    - run: pixi run test
